<?php if (count($view->chargingPoints) === 0): ?>
    <p class="text-white">No charging points found.</p>
<?php else: ?>
    <?php foreach ($view->chargingPoints as $point): ?>
        <div class="col-12 col-md-6 col-lg-3 mb-4">
            <div class="card bg-dark text-white">
                <div class="card-img-top bg-image"
                    style="background-image: url('<?= htmlspecialchars($point['image_path']) ?>');
                    background-size: cover; background-position: center; aspect-ratio: 16/9;">
                </div>
                <div class="card-body d-flex flex-column">
                    <div>
                        <h5 class="card-title"><?= htmlspecialchars($point['address']) ?></h5>
                        <p class="card-text text-secondary">Price: $<?= htmlspecialchars($point['price_per_kwh']) ?> per kWh</p>
                        <p class="card-text text-secondary">Availability: <?= $point['isAvailable'] ? 'Available' : 'Unavailable' ?></p>
                    </div>
                    <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
