<?php require('template/header.phtml') ?>
<div class="container-fluid py-5 custom-bg">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10">
            <div class="row mb-5">
                <div class="col-12">
                    <h1 class="fw-bold text-white display-5">Level 2 Chargers</h1>
                    <h2 class="text-white fs-6">Ideal for overnight charging.</h2>
                </div>
            </div>

            <h2 class="text-white fw-bold fs-3 mb-3">Available Level 2 Chargers</h2>

            <div class="row">
                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/Level 2 Charger.png'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Level 2 Charger - Location A</h5>
                                <p class="card-text text-secondary">Price: $0.20 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/Level 2 Charger.png'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Level 2 Charger - Location B</h5>
                                <p class="card-text text-secondary">Price: $0.25 per kWh</p>
                                <p class="card-text text-secondary">Availability: 6 PM - 8 AM</p>
                            </div>
                            <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/Level 2 Charger.png'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Level 2 Charger - Location C</h5>
                                <p class="card-text text-secondary">Price: $0.30 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/Level 2 Charger.png'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Level 2 Charger - Location D</h5>
                                <p class="card-text text-secondary">Price: $0.35 per kWh</p>
                                <p class="card-text text-secondary">Availability: 7 AM - 11 PM</p>
                            </div>
                            <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/Level 2 Charger.png'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Level 2 Charger - Location E</h5>
                                <p class="card-text text-secondary">Price: $0.40 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/Level 2 Charger.png'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Level 2 Charger - Location E</h5>
                                <p class="card-text text-secondary">Price: $0.40 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/Level 2 Charger.png'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Level 2 Charger - Location E</h5>
                                <p class="card-text text-secondary">Price: $0.40 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php require('template/footer.phtml') ?>
