<div class="container-fluid py-5 custom-bg">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10">

            <div class="card bg-dark text-white shadow mb-4">
                <div class="card-body p-4">
                    <h3 class="h5 mb-3">My Charging Point</h3>
                    <div id="chargingPoint">
                        <div class="card bg-secondary text-white mb-3">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <div>
                                    <p class="mb-1"><strong>Location:</strong> Manama</p>
                                    <p class="mb-1"><strong>Price:</strong> 20BD</p>
                                    <p class="mb-1"><strong>Availability:</strong> Available</p>
                                </div>
                                <div>
                                    <button class="btn btn-sm btn-outline-light fw-bold">View</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card bg-dark text-white shadow mb-4">
                <div class="card-body p-4">
                    <h3 class="h5 mb-3">All Booking Requests</h3>
                    <div id="chargingPoint">
                            <div class="card bg-secondary text-white mb-3">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <div>
                                    <p class="mb-1"><strong>Request ID:</strong> #123</p>
                                    <p class="mb-1"><strong>Request Duration:</strong> 12.3.2025 - 13.3.2025</p>
                                </div>
                                <div>
                                    <button class="btn btn-sm btn-outline-light fw-bold">View</button>
                                </div>
                            </div>
                    </div>
                    <div id="chargingPoint">
                            <div class="card bg-secondary text-white mb-3">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <div>
                                    <p class="mb-1"><strong>Request ID:</strong> #123</p>
                                    <p class="mb-1"><strong>Request Duration:</strong> 12.3.2025 - 13.3.2025</p>
                                </div>
                                <div>
                                    <button class="btn btn-sm btn-outline-light fw-bold">View</button>
                                </div>
                            </div>
                    </div>
                    <div id="chargingPoint">
                            <div class="card bg-secondary text-white mb-3">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <div>
                                    <p class="mb-1"><strong>Request ID:</strong> #123</p>
                                    <p class="mb-1"><strong>Request Duration:</strong> 12.3.2025 - 13.3.2025</p>
                                </div>
                                <div>
                                    <button class="btn btn-sm btn-outline-light fw-bold">View</button>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
</div>