<?php require('template/header.phtml') ?>
<div class="container-fluid py-5 custom-bg">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10">
            <div class="row mb-5">
                <div class="col-12">
                    <h1 class="fw-bold text-white display-5">Tesla Chargers</h1>
                    <h2 class="text-white fs-6">Compatible with Tesla vehicles.</h2>
                </div>
            </div>

            <h2 class="text-white fw-bold fs-3 mb-3">Available Tesla Chargers</h2>

            <div class="row">

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/tesla charger.webp'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Tesla Charger - Location A</h5>
                                <p class="card-text text-secondary">Price: $0.40 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <?php if ($_SESSION['role'] === 'user'): ?>
                                <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>


                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/tesla charger.webp'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Tesla Charger - Location B</h5>
                                <p class="card-text text-secondary">Price: $0.45 per kWh</p>
                                <p class="card-text text-secondary">Availability: 7 AM - 11 PM</p>
                            </div>
                            <?php if ($_SESSION['role'] === 'user'): ?>
                                <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/tesla charger.webp'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Tesla Charger - Location C</h5>
                                <p class="card-text text-secondary">Price: $0.50 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <?php if ($_SESSION['role'] === 'user'): ?>
                                <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/tesla charger.webp'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Tesla Charger - Location D</h5>
                                <p class="card-text text-secondary">Price: $0.55 per kWh</p>
                                <p class="card-text text-secondary">Availability: 6 PM - 6 AM</p>
                            </div>
                            <?php if ($_SESSION['role'] === 'user'): ?>
                                <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/tesla charger.webp'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Tesla Charger - Location E</h5>
                                <p class="card-text text-secondary">Price: $0.60 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <?php if ($_SESSION['role'] === 'user'): ?>
                                <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/tesla charger.webp'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Tesla Charger - Location E</h5>
                                <p class="card-text text-secondary">Price: $0.60 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <?php if ($_SESSION['role'] === 'user'): ?>
                                <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="card-img-top bg-image" style="background-image: url('images/tesla charger.webp'); 
                        background-size: cover; background-position: center; 
                        aspect-ratio: 16/9;">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div>
                                <h5 class="card-title">Tesla Charger - Location E</h5>
                                <p class="card-text text-secondary">Price: $0.60 per kWh</p>
                                <p class="card-text text-secondary">Availability: 24/7</p>
                            </div>
                            <?php if ($_SESSION['role'] === 'user'): ?>
                                <button class="btn custom-btn mt-4 w-100 fw-bold">Book Now</button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<?php require('template/footer.phtml') ?>
